Projeto/database/models/cliente.py
from peewee import Model, CharField,DateTimeField
from database.database import db
from datetime import datetime

class cliente(Model):
    name = CharField()
    email = CharField()
    data_criacao = DateTimeField(default=datetime.now)

    class Meta:
        database = db

Projeto/main.py
from flask import Flask
from configuration import configure_all

app = Flask(__name__)

configure_all(app)

app.run(debug=True)

Projeto/routes/cliente.py
from flask import Blueprint, render_template, request
from database.cliente import CLIENTES
from database.models import cliente

cliente_route = Blueprint('cliente', __name__)

@cliente_route.route('/')
def lista_clientes():
    """ listar os clientes """
    clientes=cliente.select()
    return render_template('lista_clientes.html', clientes=clientes)
    

@cliente_route.route('/', methods=['POST'])
def inserir_cliente():
    """ inserir os dados do cliente """
    
    data = request.json
    
    novo_usuario = {
        "id": len(CLIENTES) + 1,
        "nome": data['nome'],
        "email": data['email'],
    }
    
    CLIENTES.append(novo_usuario)
    
    return render_template('item_cliente.html', cliente=novo_usuario)
    

@cliente_route.route('/new')
def form_cliente():
    """ formulario para cadastrar um cliente """
    return render_template('form_cliente.html')
    

@cliente_route.route('/<int:cliente_id>')
def detalhe_cliente(cliente_id):
    """ exibir detalhes do cliente """
    
    cliente = list(filter(lambda c: c['id'] == cliente_id, CLIENTES))[0]
    return render_template('detalhe_cliente.html', cliente=cliente)
    

@cliente_route.route('/<int:cliente_id>/edit')
def form_edit_cliente(cliente_id):
    """ formulario para editar um cliente """
    cliente = None
    for c in CLIENTES:
        if c['id'] == cliente_id:
            cliente = c
    
    return render_template('form_cliente.html', cliente=cliente)

@cliente_route.route('/<int:cliente_id>/update', methods=['PUT'])
def atualizar_cliente(cliente_id):
    """ atualizar informacoes do cliente """
    cliente_editado = None
    # obter dados do formulario de edicao
    data = request.json
    
    # obter usuario pelo id
    for c in CLIENTES:
        if c['id'] == cliente_id:
            c['nome'] = data['nome']
            c['email'] = data['email']
            
            cliente_editado = c
            
    # editar usuario
    return render_template('item_cliente.html', cliente=cliente_editado)
    

@cliente_route.route('/<int:cliente_id>/delete', methods=['DELETE'])
def deletar_cliente(cliente_id):   
    global CLIENTES
    CLIENTES = [ c for c in CLIENTES if c['id'] != cliente_id ]
    return {'deleted': 'ok'}

Projeto/routes/home.py
from flask import Blueprint, render_template

home_route = Blueprint('home', __name__)

@home_route.route('/')
def home():
    return render_template('index.html')

Projeto/templates/detalhe_cliente.html
<ul>
    <li>ID: {{cliente.id}}</li>
    <li>NOME: {{cliente.nome}}</li>
    <li>E-MAIL: {{cliente.email}}</li>
</ul>

Projeto/templates/form_cliente.html
<form class="c-form" 
        {% if cliente %}
            action="{{ url_for('cliente.atualizar_cliente', cliente_id=cliente.id) }}" 
        {% else %}
            action="{{ url_for('cliente.inserir_cliente') }}" 
        {% endif %}

        method="{% if cliente %}PUT{% else %}POST{% endif %}"

        {% if cliente %}
            c-swap="#cliente-{{cliente.id}}"
        {% else %}
            c-append="#lista-clientes"
        {% endif %}

        c-reload-container="true">
   
    <div class="mb-3">
      <label class="form-label">Nome</label>
      <input type="text" class="form-control" name="nome" {% if cliente%}value="{{cliente.nome}}"{% endif %}>
    </div>

    <div class="mb-3">
        <label id="label-target" class="form-label">Email</label>
        <input type="text" class="form-control" name="email" {% if cliente%}value="{{cliente.email}}"{% endif %}>
    </div>
  

    <button type="submit" class="btn btn-primary">
        {% if cliente %}Salvar{% else %}Criar{% endif %}
    </button>
</form>

Projeto/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/app.css')  }}">
  </head>
  <body>
    
    <div class="container">

  
      <!-- Formulário add cliente -->
      <div id="form-cliente" 
          c-container="{{ url_for('cliente.form_cliente') }}"></div>
      
      <hr>

      <!-- Lista de clientes -->
      <h2>Lista de clientes</h2>

      <div c-container="{{ url_for('cliente.lista_clientes') }}"></div>
    </div>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body" id="exibir-cliente"></div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='js/cru.js')  }}"></script>

  </body>
</html>

Projeto/templates/item_cliente.html
<tr id="cliente-{{cliente.id}}">
    <th scope="row">{{ cliente.id }}</th>
    <td>{{ cliente.nome }}</td>
    <td>{{ cliente.email }}</td>
    <td>
        <button class="btn btn-secondary" 
            c-get="{{ url_for('cliente.detalhe_cliente', cliente_id=cliente.id) }}"
            c-target="#exibir-cliente"
            data-bs-toggle="modal" data-bs-target="#exampleModal">
                Ver
        </button>

        <button class="btn btn-primary" 
            c-get="{{ url_for('cliente.form_edit_cliente', cliente_id=cliente.id) }}"
            c-target="#form-cliente">
                Editar
        </button>

        <button class="btn btn-danger" 
            c-delete="{{ url_for('cliente.deletar_cliente', cliente_id=cliente.id) }}"
            c-remove-closest="tr">
                Deletar
        </button>
    </td>
</tr>

Projeto/templates/lista_clientes.html
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Nome</th>
        <th scope="col">Email</th>
        <th scope="col">Ações</th>
      </tr>
    </thead>
    <tbody id="lista-clientes">

        {% for cliente in clientes %}
            {% include 'item_cliente.html' %}
        {% endfor %}

    </tbody>
  </table>